# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
      - r-cran-mixomics
after_success:
  - Rscript -e 'covr::codecov()'
